//
//  ApiService+Method.swift
//  ZhiTing
//
//  Created by iMac on 2021/7/29.
//

import Foundation
import Moya



extension ApiService {
    var method: Moya.Method {
        switch self {
        case .editCloudUser:
            return .put
        case .cloudUserDetail:
            return .get
        case .brands:
            return .get
        case .brandDetail:
            return .get
        case .plugins:
            return .get
        case .deletePluginById:
            return .delete
        case .pluginDetail:
            return .get
        case .installPlugin:
            return .post
        case .deletePlugin:
            return .delete
        case .defaultLocationList:
            return .get
        case .createArea:
            return .post
        case .areaList:
            return .get
        case .areaDetail:
            return .get
        case .changeAreaName:
            return .put
        case .deleteArea:
            return .delete
        case .locationDetail:
            return .get
        case .changeLocationName:
            return .put
        case .deleteLocation:
            return .delete
        case .addLocation:
            return .post
        case .setLocationOrders:
            return .put
        case .deviceDetail:
            return .get
        case .editDevice:
            return .put
        case .locationsList:
            return .get
        case .deleteDevice:
            return .delete
        case .deviceList:
            return .get
        case .getDeviceAccessToken:
            return .post
        case .sceneList:
            return .get
        case .createScene:
            return .post
        case .deleteScene:
            return .delete
        case .sceneExecute:
            return .post
        case .sceneDetail:
            return .get
        case .editScene:
            return .put
        case .sceneLogs:
            return .get
        case .register:
            return .post
        case .login:
            return .post
        case .logout:
            return .post
        case .captcha:
            return .get
        case .getInviteQRCode:
            return .post
        case .userDetail:
            return .get
        case .memberList:
            return .get
        case .deleteMember:
            return .delete
        case .editMember:
            return .put
        case .rolesList:
            return .get
        case .quitArea:
            return .delete
        case .scanQRCode:
            return .post
        case .rolesPermissions:
            return .get
        case .syncArea:
            return .post
        case .addSADevice:
            return .post
        case .editSAUser:
            return .put
        case .checkSABindState:
            return .get
        case .bindCloud:
            return .post
        case .scopeList:
            return .get
        case .scopeToken:
            return .post
        case .transferOwner:
            return .put
        case .temporaryIP:
            return .get
        case .temporaryIPBySAID:
            return .get
        case .getSAToken:
            return .get
        case .commonDeviceList:
            return .get
        case .checkPluginUpdate:
            return .get
        case .getCaptcha:
            return .post
        case .downloadPlugin:
            return .get
        case .settingTokenAuth:
            return .put
        case .getSoftwareVersion:
            return .get
        case .getSoftwareLatestVersion:
            return .get
        case .updateSoftware:
            return .post
        case .getFirmwareLatestVersion:
            return .get
        case .getFirmwareVersion:
            return .get
        case .updateFirmware:
            return .post
        case .migrationAddr:
            return .get
        case .migrationCloudToLocal:
            return .post
        case .commonDeviceMajorList:
            return .get
        case .commonDeviceMinorList:
            return .get
        case .departmentList:
            return .get
        case .addDepartment:
            return .post
        case .departmentDetail:
            return .get
        case .addDepartmentMember:
            return .post
        case .updateDepartment:
            return .put
        case .deleteDepartment:
            return .delete
        case .setDepartmentOrders:
            return .put
        case .changePWD:
            return .put
        case .forgetPwd:
            return .post
        case .getSAExtensions:
            return .get
        case .unregister:
            return .delete
        case .unregisterList:
            return .get
        case .deleteSA:
            return .delete
        case .scUploadFile:
            return .post
        case .getAppVersions:
            return .get
        case .saUploadFile:
            return .post
        case .deviceLogoList:
            return .get
        case .getAppSupportApiVersion:
            return .get
        case .setSceneSort:
            return .put
        case .getSAStatus:
            return .get
        case .thirdPartyCloudListSC:
            return .get
        case .thirdPartyCloudListSA:
            return .get
        case .unbindThirdPartyCloud:
            return .delete
        case .getSASupportApiVersion:
            return .get
        case .feedbackList:
            return .get
        case .feedbackDetail:
            return .get
        case .createFeedback:
            return .post
        }
    }
}
